name: hello-World
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v16
      - name: run tests
        run: make test
      - name: run lint
        run: make lint