name: hello-World
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: make setup
      - run: make install
      - name: run tests
        run: make test
      - name: run lint
        run: make lint